# Generated by Django 5.0.4 on 2025-03-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastodonhub', '0002_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastodonhubclubs',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
